[package]
name = "conc-spike"
version = "0.1.0"
authors = ["Akshay Dewan <akshayde@thoughtworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
dashmap = "3.7.0"
rayon = "1.3.0"
